### ISSUE TITLE
2021 import_weekly_data column 'recent_team' returns "LA" for Rams players instead of "LAR"

### ISSUE THREAD

**Issue by ace51689** [cooperdff/nfl_data_py#29]
Not sure if this is intended, or if it extends to any prior seasons.

**Comment by alecglen** [comment]
Hi @ace51689! That is actually intentional, at least in that it's how the abbreviation comes in from the [source data](https://github.com/nflverse/nflverse-data/releases/tag/player_stats) this package references.

You'll see it's consistent across datasets if you pull e.g. the play-by-play or schedules, and it does extend back as long as the team has been in Los Angeles. (Prior to that they are labeled as "STL" for St. Louis.)
