### ISSUE TITLE
weekly pfr and ftn data

### ISSUE THREAD

**Issue by bhibby** [cooperdff/nfl_data_py#64]
hey,

getting attribute errors when trying to pull down the weekly pfr and ftn data

AttributeError: module 'nfl_data_py' has no attribute 'import_weekly_pfr'
AttributeError: module 'nfl_data_py' has no attribute 'import_ftn_data'

thoughts?
thanks

**Comment by alecglen** [comment]
Hey Bill - we just added these new methods and got them merged in here, but the new package release hasn't actually been published quite yet. (that's why they're not in the [docs on PyPI](https://pypi.org/project/nfl-data-py/))

It will be published very soon (hopefully tonight), at which point you'll be able to use the new methods after running `pip install --upgrade nfl-data-py`

**Comment by alecglen** [comment]
[v0.3.1 has been released!](https://pypi.org/project/nfl-data-py/0.3.1/)
